import Head from 'next/head'
import { Box, Container } from '@chakra-ui/react'
import Navbar from '@/components/shared/navbar/navbar'
import LayoutMain from '@/components/layouts/main'


export default function Home() {
  return (
    <>
      <Head>
        <title>Daymer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </>
  )
}
